### ISSUE TITLE
iOS AMP Viewer: Cocoapods and Project structure

### ISSUE THREAD

**Issue by alihen** [ampproject/amp-viewer#71]
I recently attempted to integrate the AMP View into an iOS project using Cocoapods. 
Added
```
pod 'AMPKit'
```
To my Podfile, and was unable to load images in the app.

I had a hunch that `master` branch of AMPKit wasn't the same as the Pod version that had been published to Cocoapods trunk, so I attempted to point the Podfile to the repo

```
pod 'AMPKit', :git => 'https://github.com/ampproject/amp-viewer.git', :branch => 'master' 
```

Unfortunately this doesn't work due to how the project has nested the files into the `ios` directory.

I'm in the process of forking the repo and fixing this in order to use it, but I'd like to raise this as an issue for future iOS developers that attempt to integrate the project. 🙂

**Questions:**
- How should the project be structured? Can Cocoapods be nested in directories? Should the iOS project sit in it's own repo?
- How are Pods published? Is someone in charge of this?

**Comment by alihen** [comment]
I've forked and implemented working cocoapods implementation of this repo at https://github.com/Superbalist/amp-viewer

It can be used in a Podfile by referencing

```
pod 'AMPKit', :git => 'https://github.com/Superbalist/amp-viewer.git', :branch => 'master'
```

**Comment by stephen-deg** [comment]
Hi @alihen 

Thanks for pointing out the issues you had. You raise a good point about the structure. Cocoapods isn't really designed to work in a repo structured in directories like the amp-viewer repo is. A year ago, I thought this was working as I checked out the Demo but it's possible it was just working due to some other setup I had.

I'll try to check again and see why it's not working and try to resolve it. Ideally, this would have a dedicated repo and I'll bring this up again and see if we can make it happen.

I also have a few bug fixes that have accrued and I need to push. I'll try to make this happen by early next week.

Finally, I published the few pod releases we've had.

Please feel free to reach out with anything else you notice. Thanks!

**Comment by stephen-deg** [comment]
Looks like there were a few issues here

1) The podspec file was out of date (listing v 0.1.0 when it should have been v0.1.1)
2) The tag was wrong on github
3) It the format of the file was slightly incorrect. Because of the structure, running
 `pod lib lint`
Doesn't always validate correctly. When Cocoapods pulls the latest tagged release, it looks from the root of the tarball, which means the spec file needs to include ios/AMPKit/... rather than just AMPKit/...
Interestingly enough, if you `pod lib lint` from the directory it will validate, but then later fail when you try to use it. 

I updated the Cocoapods trunk with the latest v0.1.1 and created a sample project where I included it in a podfile and everything seems to work fine.

I think unfortunately this will stay in the nested repo. Provided I make sure the spec file include the full directory path and that the tags are correct on Github, it should all work. 

Let me know if there's still issues.
